### ISSUE TITLE
jq: error (at <stdin>:1): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by DanielParra159** [CodelyTV/check-critical-files#2]
Hello,

I am having a problem with this action, when the action executes it throws this error: `jq: error (at <stdin>:1): Cannot iterate over null (null)`. I am not sure if I have something wrong in the workflow file or what is the problem.

Complete output:
```
 Run codelytv/check-critical-files@v11s
E N T R Y . 8
Run codelytv/check-critical-files@v1
  with:
    GITHUB_TOKEN: ***
    critical_message: Remember to update the README with the new workflow, if needed
    critical_files: workflows
   
  
/usr/bin/docker run --name d00b339cee1cd3f2bc450387a363cf926a0cf0_719c0b --label d00b33 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_CRITICAL_MESSAGE -e INPUT_CRITICAL_FILES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/HangmanGame/HangmanGame":"/github/workspace" d00b33:9cee1cd3f2bc450387a363cf926a0cf0  "***" "workflows
 
" "Remember to update the README with the new workflow, if needed"
jq: error (at <stdin>:1): Cannot iterate over null (null)
E N T R Y . 8
```

Workflow file:
```
name: Check critical files

on: [pull_request]

jobs:
  check-critical-files:
    runs-on: ubuntu-latest
    name: Check for critical files
    steps:
      - uses: codelytv/check-critical-files@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          critical_message: Remember to update the README with the current version
          critical_files: |
            ProjectVersion.txt
      - uses: codelytv/check-critical-files@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          critical_message: Remember to update the README with the new workflow, if needed
          critical_files: |
            workflows
             
```
Notice that "workflows" is a folder, I want to check all the files in the folder.
